os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.10.0"
jdk:
  - oraclejdk8
cache:
  yarn: true
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/.yarn-cache
    - node_modules

before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - export TZ=Australia/Canberra
  - date
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add yo bower gulp-cli
install:
  - cd "$TRAVIS_BUILD_DIR"/
  - yarn install
  - yarn link
  - yarn run test
  - mvn clean package
